baseURL = "https://elizabethdinella.github.io/website"
languageCode = "en"
DefaultContentLanguage = "en"
title = "Elizabeth Dinella"
theme = "anatole"
summarylength = 10
enableEmoji = true
enableRobotsTXT = true

# Enable Disqus
#disqusShortname = ""

# Google Analytics
#googleAnalytics = "UA-123-45"

[markup.goldmark.renderer]
unsafe= true

[params]
title = "Elizabeth Dinella"
description = "University Of Pennsylvania PhD Student"
profilePicture = "images/image.png"
keywords = ""
favicon = "favicons/"
customCss = []
customJs = []
mainSections = ["post"]
images = ["images/site-feature-image.png"]

[menu]

  [[menu.main]]
  name = "About Me"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Blog Posts"
  weight = 200
  identifier = "blog-posts"
  url = "/blog-posts/"

## Math settings
[params.math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links
[[params.socialIcons]]
icon = "fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/elizabeth-dinella-154772102/"

[[params.socialIcons]]
icon = "fa-twitter"
title = "Twitter"
url = "https://twitter.com/eadinella"

[[params.socialIcons]]
icon = "fa-github"
title = "GitHub"
url = "https://github.com/elizabethdinella"

[[params.socialIcons]]
icon = "fa-envelope"
title = "e-mail"
url = "mailto:edinella@seas.upenn.edu"


